### ISSUE TITLE
I have a question about omega caculation.

### ISSUE THREAD

**Issue by nfenny01** [tamu-vscl/encoder-to-speed#1]
In processVelocity function, 

omega = omega = ( (1.5)*firstPos[2] + (-2.0)*firstPos[1] + (0.5)*firstPos[0] )/h;

I don't know why multiply 1.5 and -2 and 0.5.

I understand that this equation is the part to find the amount of change in the encoder value.

I would appreciate your reply.

The source code is very helpful.

Thank you.

**Comment by viniciusguigo** [comment]
Hi nfenny01,

These are the coefficients used in the backward finite difference method to approximate the velocity using the previous 3 position readings (and the time between them). Please see the table in the Backward finite difference section, second-order derivative: https://en.wikipedia.org/wiki/Finite_difference_coefficient. As you can see, you can also add more position readings to have a better estimate of the velocity. This calculator might also be helpful: http://web.media.mit.edu/~crtaylor/calculator.html.

Glad the code is helpful. Thanks!

**Comment by viniciusguigo** [comment]
I'm closing this issue because it has been inactive for a few weeks. Please re-open it if necessary. Thanks!
